server:
  port: 8080
  servlet:
    context-path: /messaging-service

socket-server:
  host: 0.0.0.0
  port: 8081

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}

spring:
  # Postgresql Config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      show_sql: true
      format_sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.default_batch_fetch_size: 1000
      hibernate.hbm2ddl.auto: create
      default_schema: message-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

jwt:
  secret: ${JWT_SECRET}
  expiration_date: 8640000

logging:
  level:
    com.corundumstudio.socketio: debug
    web: debug

modules:
  endpoints:
    user-service:
    recommend-service:
    relation-service:
    messaging-service:

