apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-service
  namespace: backend
  labels:
    app: messaging-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-service
  template:
    metadata:
      labels:
        app: messaging-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: kyankee6/watermelon-messaging-service:76ee009
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: messaging-service-config
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: tb
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-service-head
  namespace: backend
spec:
  selector:
    app: messaging-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
